Lightning-AI/LitModels

- src/litmodels/integrations/checkpoints.py
<details>
</details>
resolve checkpointing on multi-node cluster
> fix: upload from global zero

- src/litmodels/__about__.py
<details>
</details>
pending on #56 and #55
> releasing `0.1.2`

- tests/integrations/test_cloud.py
<details>
</details>
Ensure all Trainer methods with `chpt_path`
> test: integration Trainer's resume {fit|val|test|pred} with Prod

- requirements.txt
- src/litmodels/io/cloud.py
- tests/integrations/test_cloud.py
<details>
</details>
validate that in studio you do not need to specify teamspace
> tests: integrations as running in studio

- src/litmodels/io/gateway.py
- tests/test_io_cloud.py
<details>
</details>
simplify user experience when uploading TorchScript model
> simple upload & load TorchScript model

- src/litmodels/integrations/mixins.py
- tests/integrations/test_mixins.py
<details>
</details>
Simplify integration with custom models
> adding Pickle mixin

- src/litmodels/integrations/mixins.py
- tests/integrations/test_mixins.py
<details>
</details>
simplify usage of torch `nn.Module`
> adding Torch mixin

- README.md
<details>
</details>
Showcase what 
> update Readme with Mixins

- README.md
- requirements.txt
- src/litmodels/integrations/mixins.py
- src/litmodels/io/cloud.py
- tests/integrations/test_mixins.py
<details>
</details>
prevent accidentally uploading other files in temp folder
> update uploading multiple files for mixins

- README.md
- src/litmodels/integrations/checkpoints.py
- tests/integrations/__init__.py
- tests/integrations/test_checkpoints.py
- tests/integrations/test_cloud.py
<details>
</details>
asked by Will to not force user to use any name if feasible
> enable empty checkpoint name

- .github/workflows/ci-cloud.yml
<details>
</details>
improve perception about package coverage/testing
> collect Codecov also from integrations tests

- tests/integrations/test_cloud.py
<details>
</details>
cover integration case for a new user and improve codecoverage
> adding `test_list_available_teamspaces`

- README.md
- _requirements/test.txt
- examples/demo-tensorflow-keras.py
- src/litmodels/io/gateway.py
- src/litmodels/io/utils.py
- tests/integrations/test_cloud.py
- tests/test_io_cloud.py
<details>
</details>
* Support for saving and uploading models in `.keras` formats.
* Simple API to load models directly from Model Hub into `tf.keras.Model` objects.
* Automatic format detection and validation during load.
* Example usage and docs included.
This streamlines model sharing and reuse, making it easier to distribute and deploy TensorFlow models through Model Hub.
> feat: save/load TF Keras model

- README.md
<details>
</details>
Improve clarity why this package is useful/needed
> update readme with clarity

- README.md
<details>
</details>
Fixes readme toy example
> nitpick: fix readme toy example

- requirements.txt
- src/litmodels/io/cloud.py
<details>
</details>
covering breaking change with non-public API
> fix compatibility with SDK, `_parse_org_teamspace_model_version`

- src/litmodels/__init__.py
- src/litmodels/io/__init__.py
<details>
</details>
Completing the user stories
> expose `upload_model_files` in the pkg root

- .github/dependabot.yml
<details>
</details>
Drop deprecated argument
> Update dependabot - drop reviewer

- src/litmodels/io/utils.py
<details>
</details>
Fixes #96
Suppress the logging output from tensorflow/keras when we check if the modules are available for import. This should therefore not influence user code that uses tensorflow/keras which may generate errors. 
> update integration with Tensorflow

- src/litmodels/io/utils.py
- tests/integrations/test_real_cloud.py
<details>
</details>
Fixes #119
> typing: fix missing
